// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class ClientSideTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private WebDriverWait wait;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\pietr\\Desktop\\chromedriver-win64\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
    wait = new WebDriverWait(driver, Duration.ofSeconds(10).toSeconds()); // Attesa fino a 10 secondi
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tC13() {
    driver.get("http://localhost:8080/murmur_war_exploded/home.jsp");
    driver.manage().window().setSize(new Dimension(786, 816));

    // Aspetta che il dropdown sia cliccabile
    WebElement pageDropdown = wait.until(ExpectedConditions.elementToBeClickable(By.id("pageNameSelect")));
    pageDropdown.click();
    pageDropdown.findElement(By.xpath("//option[. = 'Search Page']")).click();

    WebElement scheduleType = wait.until(ExpectedConditions.elementToBeClickable(By.id("searchScheduleType")));
    scheduleType.click();
    scheduleType.findElement(By.xpath("//option[. = 'Daily']")).click();

    WebElement serviceMode = wait.until(ExpectedConditions.elementToBeClickable(By.id("searchServiceMode")));
    serviceMode.click();

    scheduleType = wait.until(ExpectedConditions.elementToBeClickable(By.id("searchScheduleType")));
    scheduleType.click();
    scheduleType.findElement(By.xpath("//option[. = 'Weekly']")).click();

    serviceMode = wait.until(ExpectedConditions.elementToBeClickable(By.id("searchServiceMode")));
    serviceMode.click();
    serviceMode.findElement(By.xpath("//option[. = 'Home Delivery']")).click();

    WebElement profession = wait.until(ExpectedConditions.elementToBeClickable(By.id("professionCriteria")));
    profession.click();
    profession.sendKeys("Idraulico23");

    WebElement hourlyMin = wait.until(ExpectedConditions.elementToBeClickable(By.id("hourlyRateMin")));
    hourlyMin.click();
    hourlyMin.sendKeys("10");

    WebElement hourlyMax = wait.until(ExpectedConditions.elementToBeClickable(By.id("hourlyRateMax")));
    hourlyMax.click();
    hourlyMax.sendKeys("15");

    WebElement startDate = wait.until(ExpectedConditions.elementToBeClickable(By.id("startDate")));
    startDate.click();
    startDate.sendKeys("2025-02-20");

    WebElement endDate = wait.until(ExpectedConditions.elementToBeClickable(By.id("endDate")));
    endDate.click();
    endDate.sendKeys("2025-06-18");
    endDate.click();
    endDate.sendKeys("2025-06-20");

    WebElement monday = wait.until(ExpectedConditions.elementToBeClickable(By.id("monday")));
    monday.click();

    WebElement mondayStart = wait.until(ExpectedConditions.elementToBeClickable(By.name("mondayStart")));
    mondayStart.click();
    mondayStart.sendKeys("12:05");

    WebElement mondayEnd = wait.until(ExpectedConditions.elementToBeClickable(By.name("mondayEnd")));
    mondayEnd.click();
    mondayEnd.sendKeys("19:06");

    WebElement results = wait.until(ExpectedConditions.elementToBeClickable(By.id("results")));
    results.click();

    WebElement city = wait.until(ExpectedConditions.elementToBeClickable(By.id("city")));
    city.click();
    city.sendKeys("Gragnano");

    WebElement street = wait.until(ExpectedConditions.elementToBeClickable(By.id("street")));
    street.click();
    street.sendKeys("Via Vittorio Veneto");

    WebElement district = wait.until(ExpectedConditions.elementToBeClickable(By.id("district")));
    district.click();
    district.sendKeys("Napoli");

    WebElement region = wait.until(ExpectedConditions.elementToBeClickable(By.id("region")));
    region.click();
    region.sendKeys("Campania");

    WebElement country = wait.until(ExpectedConditions.elementToBeClickable(By.id("country")));
    country.click();
    country.sendKeys("Italia");

    WebElement submit = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".submit-row > input")));
    submit.click();
  }
}